spring:
  application:
    name: this is a v2ray-controller demo for private
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  thymeleaf:
    check-template: false
    check-template-location: false
    suffix: .html
    cache: false
    prefix: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8201